source ~/.files/zsh/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
  git
  ant
  bower
  docker
  grunt
  node
  npm
  sudo
  systemd
  vundle
  zsh-users/zsh-syntax-highlighting
  history-substring-search
  tarruda/zsh-autosuggestions
EOBUNDLES

antigen theme robbyrussell

antigen apply

export PATH="/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/mboyle/.local/bin:/home/mboyle/bin:/usr/local/share/scala/bin"

# Preferred editor for local and remote sessions
export EDITOR='vim'

zle-line-init() {
  zle autosuggest-start
}
zle -N zle-line-init
bindkey '^T' autosuggest-toggle

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

COMPLETION_WAITING_DOTS=false
