source ~/.files/zsh/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
  git
  ant
  bower
  docker
  grunt
  node
  npm
  sudo
  systemd
  vundle
  zsh-users/zsh-syntax-highlighting
EOBUNDLES

antigen theme robbyrussell

antigen apply

export PATH="/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/mboyle/.local/bin:/home/mboyle/bin:/usr/local/share/scala/bin"

# Preferred editor for local and remote sessions
export EDITOR='vim'

COMPLETION_WAITING_DOTS=false
